/*
 * SPDX-FileCopyrightText: 2026 Rayleigh Research <to@rayleigh.re>
 * SPDX-License-Identifier: MIT
 */

/*
 * `run/config/reference.xml` carries every attribute the loader reads, at the value the engine
 * would use anyway, so that "what can I actually set" has an answer that is not a source read.
 * It is generated by tools/config_inventory.py, and generated files rot in a specific way: the
 * generator keeps working, the file keeps looking plausible, and nothing notices that it stopped
 * describing the code. It is also the file people copy from, so a broken one propagates.
 *
 * What is asserted: the file parses, and every name in it is one the loader asks for. That is
 * the same check the loader performs at startup, aimed at the file meant to be exemplary.
 *
 * What is NOT asserted, and why. END-TO-END LOADABILITY. The reference is built from the
 * shipped config, which uses `<FundamentalPrice>`, and that process needs the SharedResources
 * owned by SimulationManager, so a bare Simulation cannot host it. Standing one up here would
 * make this an integration test with a POSIX IPC object, which is exactly what these fixtures
 * avoid. The gap is real: a default that the loader would reject is not caught here.
 *
 * Nor a comparison against the current source. That needs the Python generator and belongs in
 * CI; failing here would only say "somebody added a parameter", which is not a test failure.
 *
 * Parsed with pugixml directly rather than through `util::parseSimulationFile`. That helper
 * asserts `Books@algorithm == "PriceTime"`, which the SHIPPED config does not satisfy: the
 * attribute is read nowhere in the engine, every test fixture sets it, `simulation_0.xml` does
 * not, and the matching algorithm is not selectable in the first place. Building the reference
 * to satisfy an assert the engine does not make would teach a requirement that does not exist.
 *
 * Driven through a bare Simulation, so no POSIX IPC object is created and the test cannot
 * collide with another taosim on the host.
 */

#include <taosim/xml/helpers.hpp>

#include "Simulation.hpp"

#include <pugixml.hpp>

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <filesystem>
#include <memory>
#include <set>
#include <string>

//-------------------------------------------------------------------------

using namespace taosim;
using namespace testing;

namespace fs = std::filesystem;

//-------------------------------------------------------------------------

static const auto s_referencePath =
    fs::path{__FILE__}.parent_path().parent_path().parent_path() / "run" / "config" / "reference.xml";

// The public tree carries `simulation_0.xml` alone: neither the reference nor the private-engine
// config beside it is distributed there, so both cases below would fail on a missing subject rather
// than on anything about the file. A test whose subject is absent has nothing to assert.
//
// Absence must not become a silent way for the reference to rot out of a FULL tree, though, which
// is what an unconditional `if (!exists) skip` would buy. So the skip is conditional on the tree
// being the reduced one, discriminated by a config that only a full tree carries -- there, a
// missing reference still fails the ASSERT below, which is the case worth catching.
static bool referenceIsDistributedHere()
{
    return fs::exists(s_referencePath.parent_path() / "exchange_0.xml");
}

//-------------------------------------------------------------------------

// Every name in it is one the loader asks for. This is the check the startup warning performs,
// aimed at the file that is meant to be the example: a reference config that itself carries a
// dead attribute would teach the mistake it exists to prevent.
TEST(ReferenceConfigTest, CarriesNoAttributeThatNothingReads)
{
    if (!referenceIsDistributedHere()) {
        GTEST_SKIP() << "run/config/ is reduced here; the reference is not distributed";
    }

    ASSERT_TRUE(fs::exists(s_referencePath))
        << s_referencePath << " is missing; regenerate it with tools/config_inventory.py";

    pugi::xml_document doc;
    ASSERT_TRUE(doc.load_file(s_referencePath.c_str()));
    EXPECT_EQ(taosim::xml::warnOnUnknownAttributes(taosim::xml::rootNode(doc), "reference.xml"), 0u)
        << "the reference config names attributes nothing reads; see the CONFIG lines above";
}

//-------------------------------------------------------------------------

// The generator adds every optional attribute at its default, so the reference should differ
// from its base ONLY by additions. A structural change means the generator started rewriting
// the config rather than annotating it, which would quietly make the diff against the shipped
// config meaningless -- and that diff is the whole point of the file.
TEST(ReferenceConfigTest, AddsToItsBaseWithoutRestructuringIt)
{
    if (!referenceIsDistributedHere()) {
        GTEST_SKIP() << "run/config/ is reduced here; the reference is not distributed";
    }

    static const auto basePath = s_referencePath.parent_path() / "simulation_0.xml";
    ASSERT_TRUE(fs::exists(basePath));

    const auto elements = [](const fs::path& path) {
        pugi::xml_document doc;
        EXPECT_TRUE(doc.load_file(path.c_str()));
        std::multiset<std::string> names;
        for (const auto& node : taosim::xml::rootNode(doc).select_nodes("//*")) {
            names.emplace(node.node().name());
        }
        return names;
    };

    EXPECT_EQ(elements(s_referencePath), elements(basePath))
        << "the reference no longer has the same elements as the config it is generated from";
}
