# SPDX-FileCopyrightText: 2025 Rayleigh Research <to@rayleigh.re>
# SPDX-License-Identifier: MIT
"""
Classes representing events occurring in the simulation are defined here.
"""
from taos.common.protocol import BaseModel
from pydantic import Field
from typing import Literal
from taos.im.protocol.simulator import *
from taos.common.protocol import SimulationEvent
from taos.im.utils import duration_from_timestamp
from taos.im.protocol.exchange.models import LoanSettlementOption, OrderCurrency


def abbreviate(type_name : str):
    """Compress a message type to its notice code: first letter of each ``_`` part.

    Args:
        type_name (str): e.g. ``RESPONSE_DISTRIBUTED_CANCEL_ORDERS``.

    Returns:
        str: e.g. ``RDCO``.
    """
    return ''.join([s[0] for s in type_name.split('_')])
class ExchangeEvent(SimulationEvent):
    """
    Base class for representing market events occurring in the simulation.
    """            
    @classmethod
    def from_json(self, json : dict):
        """
        Method to transform agent event messages generated by simulator to the format required by the MarketSimulationStateUpdate synapse.
        """
        t = json['y'] if 'y' in json else json['type']
        match t:
            case "RESPONSE_DISTRIBUTED_PLACE_ORDER_LIMIT" | "ERROR_RESPONSE_DISTRIBUTED_PLACE_ORDER_LIMIT":
                return LimitOrderPlacementEvent.from_json(json)
            case "RDPOL" | "ERDPOL":
                return LimitOrderPlacementEvent.model_construct(**json)
            case "RESPONSE_DISTRIBUTED_PLACE_ORDER_MARKET" | "ERROR_RESPONSE_DISTRIBUTED_PLACE_ORDER_MARKET":
                return MarketOrderPlacementEvent.from_json(json)
            case "RDPOM" | "ERDPOM":
                json['r'] = OrderCurrency(json['r'])
                return MarketOrderPlacementEvent.model_construct(**json)
            case "EVENT_TRADE":
                return TradeEvent.from_json(json)
            case "ET":
                return TradeEvent.model_construct(**json)
            case "RESPONSE_DISTRIBUTED_CANCEL_ORDERS" | "ERROR_RESPONSE_DISTRIBUTED_CANCEL_ORDERS":
                return OrderCancellationsEvent.from_json(json)
            # model_construct skips validation, which is what the abbreviated wire form wants for
            # scalars but leaves a container's items as raw dicts. The dispatcher hands those items to
            # the miner's handler one at a time, and a handler reads `cancellation.orderId`, so the items
            # have to be events too.
            case "RDCO" | "ERDCO":
                _ev = OrderCancellationsEvent.model_construct(**json)
                _ev.c = [OrderCancellationEvent.model_construct(**_i) if isinstance(_i, dict) else _i
                         for _i in (_ev.c or [])]
                return _ev

class OrderPlacementEvent(ExchangeEvent):
    """
    Base class for representing events corresponding to placement of an order in the simulation.

    Attributes:
        bookId (int | None): The ID of the orderbook on which the order was attempted to be placed.
        orderId (int | None): The ID assigned to the order by the simulator.
        clientOrderId (int | None): Optional agent-assigned identifier for the order.
        side (int): The side of the book on which the order was attempted to be placed (0=BID, 1=ASK).
        quantity (float): The size of the order in base currency.
        success (bool): Flag indicating if the order was successfully placed or not.
        message (str): The message associated with the failure in case of unsuccessful placement.
    """
    b : int | None = Field(alias="bookId", default=None)
    o : int | None = Field(alias="orderId")
    c : int | None = Field(alias="clientOrderId")
    d : str = Field(alias="delegate", default=None)
    s : int = Field(alias="side")
    q : float = Field(alias="quantity")
    u : bool = Field(alias="success")
    m : str = Field(alias="message")
    
    @property
    def bookId(self) -> int | None:
        """Readable accessor for wire field ``b``; ``bookId`` is its serialized alias."""
        return self.b
    
    @property
    def orderId(self) -> int | None:
        """Readable accessor for wire field ``o``; ``orderId`` is its serialized alias."""
        return self.o
    
    @property
    def clientOrderId(self) -> int | None:
        """Readable accessor for wire field ``c``; ``clientOrderId`` is its serialized alias."""
        return self.c
    
    @property
    def delegate(self) -> str | None:
        """Readable accessor for wire field ``d``; ``delegate`` is its serialized alias."""
        return self.d
    
    @property
    def side(self) -> int:
        """Readable accessor for wire field ``s``; ``side`` is its serialized alias."""
        return self.s
    
    @property
    def quantity(self) -> float:
        """Readable accessor for wire field ``q``; ``quantity`` is its serialized alias."""
        return self.q
    
    @property
    def success(self) -> bool:
        """Readable accessor for wire field ``u``; ``success`` is its serialized alias."""
        return self.u
    
    @property
    def message(self) -> str:
        """Readable accessor for wire field ``m``; ``message`` is its serialized alias."""
        return self.m

class LimitOrderPlacementEvent(OrderPlacementEvent):
    """
    Represents the event generated on placement of a Limit Order in the simulation.

    Attributes:
        price (float): The price level at which the order was attempted to be placed.
    """
    y : Literal['RDPOL', 'ERDPOL'] = Field(alias="type", default='RDPOL')
    p : float = Field(alias="price")
    
    @property
    def price(self) -> float:
        """Readable accessor for wire field ``p``; ``price`` is its serialized alias."""
        return self.p
            
    @classmethod
    def from_json(self, json : dict):
        """
        Method to transform simulator format event message to the format required by the MarketSimulationStateUpdate synapse.
        """
        if json['type'] == 'RESPONSE_DISTRIBUTED_PLACE_ORDER_LIMIT':
            return LimitOrderPlacementEvent.model_construct(
                type=abbreviate(json['type']), timestamp=json['timestamp'], agentId=json['payload']['agentId'],
                bookId=json['payload']['payload']['requestPayload']['bookId'],
                orderId=json['payload']['payload']['orderId'], clientOrderId=json['payload']['payload']['requestPayload']['clientOrderId'],
                delegate=json['payload']['payload']['delegate'],
                side=json['payload']['payload']['requestPayload']['direction'],
                price=json['payload']['payload']['requestPayload']['price'],quantity=json['payload']['payload']['requestPayload']['volume'],
                success=True,message=''
            )
        elif json['type'] == 'ERROR_RESPONSE_DISTRIBUTED_PLACE_ORDER_LIMIT':
            return LimitOrderPlacementEvent.model_construct(
                type=abbreviate(json['type']), timestamp=json['timestamp'], agentId=json['payload']['agentId'],
                bookId=json['payload']['payload']['requestPayload']['bookId'],
                orderId=None,clientOrderId=json['payload']['payload']['requestPayload']['clientOrderId'],
                delegate=json['payload']['payload']['delegate'],
                side=json['payload']['payload']['requestPayload']['direction'],
                price=json['payload']['payload']['requestPayload']['price'],quantity=json['payload']['payload']['requestPayload']['volume'],
                success=False,message=json['payload']['payload']['errorPayload']['message']
            )
        
    def __str__(self):
        return f"{'PLACED' if self.success else 'FAILED TO PLACE'} {'BUY ' if self.side == 0 else 'SELL'} LIMIT ORDER{' #'+str(self.orderId) if self.orderId else ''}{' ('+str(self.clientOrderId)+')' if self.clientOrderId else ''} FOR {self.quantity}@{self.price} AT {duration_from_timestamp(self.timestamp)} (T={self.timestamp}){' : ' + self.message if not self.success else ''}"
        
class MarketOrderPlacementEvent(OrderPlacementEvent):
    """
    Represents the event generated on placement of a Market Order in the simulation.

    Attributes:
        currency (OrderCurrency): Indicator for the currecy used to specify the market order quantity
    """            
    y : Literal['RDPOM', 'ERDPOM'] = Field(alias="type", default='RDPOM')
    r : OrderCurrency = Field(alias="currency")
    l : float = Field(alias="max_slippage")
    
    @property
    def currency(self) -> OrderCurrency:
        """Readable accessor for wire field ``r``; ``currency`` is its serialized alias."""
        return self.r

    @classmethod
    def from_json(self, json : dict):
        """
        Method to transform simulator format event message to the format required by the MarketSimulationStateUpdate synapse.
        """
        if json['type'] == 'RESPONSE_DISTRIBUTED_PLACE_ORDER_MARKET':
            return MarketOrderPlacementEvent.model_construct(
                type=abbreviate(json['type']), timestamp=json['timestamp'], agentId=json['payload']['agentId'],
                bookId=json['payload']['payload']['requestPayload']['bookId'],
                orderId=json['payload']['payload']['orderId'],clientOrderId=json['payload']['payload']['requestPayload']['clientOrderId'],
                delegate=json['payload']['payload']['delegate'], max_slippage=json['payload']['payload']['requestPayload']['max_slippage'],
                side=json['payload']['payload']['requestPayload']['direction'],
                currency=json['payload']['payload']['requestPayload']['currency'],quantity=json['payload']['payload']['requestPayload']['volume'],
                success=True,message=''
            )
        elif json['type'] == 'ERROR_RESPONSE_DISTRIBUTED_PLACE_ORDER_MARKET':
            return MarketOrderPlacementEvent.model_construct(
                type=abbreviate(json['type']), timestamp=json['timestamp'], agentId=json['payload']['agentId'],
                bookId=json['payload']['payload']['requestPayload']['bookId'],
                orderId=None,clientOrderId=json['payload']['payload']['requestPayload']['clientOrderId'],
                delegate=json['payload']['payload']['delegate'], max_slippage=json['payload']['payload']['requestPayload']['max_slippage'],
                side=json['payload']['payload']['requestPayload']['direction'],
                currency=json['payload']['payload']['requestPayload']['currency'],quantity=json['payload']['payload']['requestPayload']['volume'],
                success=False,message=json['payload']['payload']['errorPayload']['message']
            )
        
    def __str__(self):
        return f"{'PLACED' if self.success else 'FAILED TO PLACE'} {'BUY ' if self.side == 0 else 'SELL'} MARKET ORDER{' #'+str(self.orderId) if self.orderId else ''}{' ('+str(self.clientOrderId)+')' if self.clientOrderId else ''} FOR {self.quantity}{'' if self.currency==OrderCurrency.ALPHA else ' TAO'} AT {duration_from_timestamp(self.timestamp)} (T={self.timestamp}){' : ' + self.message if not self.success else ''}"
        
class OrderCancellationEvent(BaseModel):
    """
    Represents cancellation of a single order.

    Attributes:
        timestamp (int): The timestamp at which cancellation was attempted.
        bookId (int): The ID of the orderbook on which the order was attempted to be cancelled.
        orderId (int): The ID of the order attempted to be cancelled.
        quantity (float | None): The quantity of the order to be cancelled, in base currency. If `None`, the entire remaining size is cancelled.
        success (bool): Flag indicating if the order was successfully cancelled or not.
        message (str): The message associated with failure in case of unsuccessful cancellation.
    """
    y : Literal['RDCO1'] = Field(alias="type", default='RDCO1')
    t : int = Field(alias="timestamp")
    b : int = Field(alias="bookId")
    o : int = Field(alias="orderId")
    q : float | None = Field(alias="quantity")
    u : bool = Field(alias="success")
    m : str = Field(alias="message")
    
    @property
    def timestamp(self) -> int:
        """Readable accessor for wire field ``t``; ``timestamp`` is its serialized alias."""
        return self.t
    
    @property
    def bookId(self) -> int:
        """Readable accessor for wire field ``b``; ``bookId`` is its serialized alias."""
        return self.b
    
    @property
    def orderId(self) -> int:
        """Readable accessor for wire field ``o``; ``orderId`` is its serialized alias."""
        return self.o
    
    @property
    def quantity(self) -> float | None:
        """Readable accessor for wire field ``q``; ``quantity`` is its serialized alias."""
        return self.q
    
    @property
    def success(self) -> bool:
        """Readable accessor for wire field ``u``; ``success`` is its serialized alias."""
        return self.u
    
    @property
    def message(self) -> str:
        """Readable accessor for wire field ``m``; ``message`` is its serialized alias."""
        return self.m

    def __str__(self):
        return f"{'CANCELLED' if self.success else 'FAILED TO CANCEL'} ORDER #{self.orderId}{' FOR ' + str(self.quantity) if self.quantity else ''} AT {duration_from_timestamp(self.timestamp)} (T={self.timestamp}){' : ' + self.message if not self.success else ''}"
        
class OrderCancellationsEvent(ExchangeEvent):
    """
    Represents the event generated on cancellation of a list of orders.

    Attributes:
        bookId (int | None): The ID of the orderbook on which the orders were attempted to be cancelled.
        cancellations (list[OrderCancellationEvent]): A list of individual order cancellation events.
    """
    y : Literal['RDCO','ERDCO'] = Field(alias="type", default='RDCO')
    b : int | None = Field(alias="bookId", default=None)
    c : list[OrderCancellationEvent] = Field(alias="cancellations", default=[])
    
    @property
    def bookId(self) -> int | None:
        """Readable accessor for wire field ``b``; ``bookId`` is its serialized alias."""
        return self.b
    
    @property
    def cancellations(self) -> list[OrderCancellationEvent]:
        """Readable accessor for wire field ``c``; ``cancellations`` is its serialized alias."""
        return self.c
    
    @classmethod
    def from_json(self, json : dict):
        """
        Method to transform simulator format event message to the format required by the MarketSimulationStateUpdate synapse.
        """
        event = OrderCancellationsEvent(type=abbreviate(json['type']), timestamp=json['timestamp'], agentId=json['payload']['agentId'], bookId=json['payload']['payload']['requestPayload']['bookId'])
        if json['type'] == 'RESPONSE_DISTRIBUTED_CANCEL_ORDERS':
            for cancellation in json['payload']['payload']['requestPayload']['cancellations']:
                event.cancellations.append(
                    OrderCancellationEvent.model_construct( timestamp=event.timestamp,
                        bookId=event.bookId, orderId=cancellation['orderId'],quantity=cancellation['volume'],
                        success=True,message=''
                    )
                )
        elif json['type'] == 'ERROR_RESPONSE_DISTRIBUTED_CANCEL_ORDERS':
            for cancellation in json['payload']['payload']['requestPayload']['cancellations']:
                event.cancellations.append(
                    OrderCancellationEvent.model_construct( timestamp=event.timestamp,
                        bookId=event.bookId, orderId=cancellation['orderId'],quantity=cancellation['volume'],
                        success=False,message=f"Order Id does not exist!"
                    )
                )
        return event
    
    def __str__(self):
        return "\n".join([f"{c}" for c in self.cancellations])
    
class TradeEvent(ExchangeEvent):
    """
    Represents the event generated on execution of trade in the simulation.

    Attributes:
        bookId (int | None): The ID of the orderbook on which the trade occurred.
        tradeId (int): The ID of the trade as assigned by the simulator.
        clientOrderId (int | None): Optional agent-assigned identifier for the resting order which was traded.
        takerAgentId (int): The ID of the agent which initiated the trade (aggressor).
        takerOrderId (int): The ID of the aggressing order involved in the trade.
        takerFee (float): The fee paid by the agent which placed the aggressing order.
        makerAgentId (int): The ID of the agent which placed the resting order involved in the trade.
        makerOrderId (int): The ID of the resting order involved in the trade.
        makerFee (float): The fee paid by the agent which placed the resting order.
        side (int): The direction of the trade; 0 if buy-initiated, otherwise 1.
        price (float): The price level at which the trade occurred.
        quantity (float): The quantity traded in base currency.
    """
    y : Literal['ET'] = Field(alias="type", default='ET')
    b : int | None = Field(alias="bookId", default=None)
    i : int = Field(alias="tradeId")
    c : int | None = Field(alias="clientOrderId", default=None)
    d : str = Field(alias="delegate")
    Ta : int = Field(alias="takerAgentId")
    Ti : int = Field(alias="takerOrderId")
    Tf : float = Field(alias="takerFee")
    Ma : int = Field(alias="makerAgentId")
    Mi : int = Field(alias="makerOrderId")
    Mf : float = Field(alias="makerFee")
    s : int = Field(alias="side")
    p : float = Field(alias="price")
    q : float = Field(alias="quantity")
    
    @property
    def bookId(self) -> int | None:
        """Readable accessor for wire field ``b``; ``bookId`` is its serialized alias."""
        return self.b
    
    @property
    def tradeId(self) -> int:
        """Readable accessor for wire field ``i``; ``tradeId`` is its serialized alias."""
        return self.i
    
    @property
    def clientOrderId(self) -> int | None:
        """Readable accessor for wire field ``c``; ``clientOrderId`` is its serialized alias."""
        return self.c
    
    @property
    def delegate(self) -> str | None:
        """Readable accessor for wire field ``d``; ``delegate`` is its serialized alias."""
        return self.d
    
    @property
    def takerAgentId(self) ->int:
        """Readable accessor for wire field ``Ta``; ``takerAgentId`` is its serialized alias."""
        return self.Ta
    
    @property
    def takerOrderId(self) ->int:
        """Readable accessor for wire field ``Ti``; ``takerOrderId`` is its serialized alias."""
        return self.Ti
    
    @property
    def takerFee(self) ->float:
        """Readable accessor for wire field ``Tf``; ``takerFee`` is its serialized alias."""
        return self.Tf
    
    @property
    def makerAgentId(self) ->int:
        """Readable accessor for wire field ``Ma``; ``makerAgentId`` is its serialized alias."""
        return self.Ma
    
    @property
    def makerOrderId(self) ->int:
        """Readable accessor for wire field ``Mi``; ``makerOrderId`` is its serialized alias."""
        return self.Mi
    
    @property
    def makerFee(self) ->float:
        """Readable accessor for wire field ``Mf``; ``makerFee`` is its serialized alias."""
        return self.Mf
    
    @property
    def side(self) ->int:
        """Readable accessor for wire field ``s``; ``side`` is its serialized alias."""
        return self.s
    
    @property
    def price(self) ->float:
        """Readable accessor for wire field ``p``; ``price`` is its serialized alias."""
        return self.p
    
    @property
    def quantity(self) ->float:
        """Readable accessor for wire field ``q``; ``quantity`` is its serialized alias."""
        return self.q
    
    @property
    def makerFeeRate(self) ->float:
        """The maker fee as a rate (fee amount over traded notional)."""
        return self.makerFee / (self.quantity * self.price)
    
    @property
    def takerFeeRate(self) ->float:
        """The taker fee as a rate (fee amount over traded notional)."""
        return self.takerFee / (self.quantity * self.price)
    
    @classmethod
    def from_json(self, json : dict):
        """
        Method to transform simulator format event message to the format required by the MarketSimulationStateUpdate synapse.
        """
        return TradeEvent.model_construct(
            type=abbreviate(json['type']), timestamp=json['timestamp'], agentId=json['payload']['agentId'],
            bookId=json['payload']['payload']['bookId'], tradeId=json['payload']['payload']['trade']['tradeId'], 
            clientOrderId=json['payload']['payload']['clientOrderId'],
            delegate=json['payload']['payload']['delegate'],
            takerAgentId=json['payload']['payload']['context']['aggressingAgentId'], takerOrderId=json['payload']['payload']['trade']['aggressingOrderId'],
            makerAgentId=json['payload']['payload']['context']['restingAgentId'], makerOrderId=json['payload']['payload']['trade']['restingOrderId'],
            side=json['payload']['payload']['trade']['direction'],price=json['payload']['payload']['trade']['price'],quantity=json['payload']['payload']['trade']['volume'],
            makerFee=json['payload']['payload']['context']['fees']['maker'], takerFee=json['payload']['payload']['context']['fees']['taker']
        )
    
    def __str__(self):
        return f"{'BUY ' if self.side == 0 else 'SELL'} TRADE #{self.tradeId} : AGGRESSIVE ORDER #{self.takerOrderId} (AGENT {self.takerAgentId}) MATCHED AGAINST #{self.makerOrderId} (AGENT {self.makerAgentId}) FOR {self.quantity}@{self.price} AT {duration_from_timestamp(self.timestamp)} (T={self.timestamp})"
    

from typing import Optional
from taos.im.protocol.models import EventHistory

# ONE AgentEventHistory, NOT TWO. This module used to define its own copy, identical to the one in
# taos/im/protocol/events.py down to the base class it imports from there. Two classes of the same name
# meant `from taos.im.protocol.agents import *` followed by `from taos.im.protocol.exchange import *`
# silently decided which one an agent got, by import order. While one copy tolerated dict-shaped notices
# and the other did not, that choice was the difference between an agent working and losing its whole
# response on every exchange tick. Notices now parse to models on both paths so neither copy needs a
# shim, and re-exporting the canonical class removes the ambiguity rather than leaving two that merely
# happen to agree.
from taos.im.protocol.events import AgentEventHistory  # noqa: F401



def _NOTICE_FACTORY_LIST():
    out = [ExchangeEvent.from_json]
    try:
        from taos.im.protocol.events import FinanceEvent

        out.append(FinanceEvent.from_json)
    except Exception:
        pass
    return out


def parse_notices(raw):
    """Build event models from the notices carried on a state update, keyed by int uid.

    NOTICES ARRIVE AS JSON-SHAPED DICTS ON EVERY PATH, because both compress() and decompress() go
    through msgpack. Handing those dicts straight to consumers made every reader ask what shape it had
    received, and dict keys stringified in transit made a uid lookup miss unless it was tried twice.
    Parsing here gives one shape and one key type, so `.type` and `notices[uid]` just work.

    A notice whose type the protocol does not recognise is dropped rather than passed through as a raw
    dict: every consumer selects by type, so an unparseable notice is unreadable anyway, and keeping it
    would reintroduce the mixed shape this exists to remove. Dropping is counted and logged, never
    silent.
    """
    if not raw:
        return raw
    out = {}
    unparsed = 0
    _NOTICE_FACTORIES = _NOTICE_FACTORY_LIST()
    for uid, events in raw.items():
        try:
            key = int(uid)
        except (TypeError, ValueError):
            key = uid
        parsed = []
        for event in events or []:
            if not isinstance(event, dict):
                parsed.append(event)
                continue
            built = None
            for factory in _NOTICE_FACTORIES:
                try:
                    built = factory(event)
                except (KeyError, TypeError, ValueError):
                    built = None
                if built is not None:
                    break
            # NEVER DROP A NOTICE. An earlier version skipped anything the local dispatcher did not
            # recognise, on the reasoning that consumers select by type so an unparsed notice is
            # unreadable anyway. That was wrong twice over: it is perfectly readable as a dict, and this
            # tree's dispatcher does not cover every code that reaches it -- the exchange one has no
            # ClosePositionsEvent, so RDCP was discarded and an SL/TP trigger's close notice never
            # reached the miner. The other tree is tried second, and a code neither knows is passed
            # through unchanged and reported, because losing a miner's notice is worse than a mixed shape.
            if built is None:
                unparsed += 1
                parsed.append(event)
                continue
            parsed.append(built)
        out[key] = parsed
    if unparsed:
        try:
            import bittensor as bt

            bt.logging.warning(f"Dropped {unparsed} notice(s) of unrecognised type while parsing")
        except Exception:
            pass
    return out
